### PR TITLE
Prepare front-end for deployment

### PR DESCRIPTION
**Pull request by xkb**

### CODE REVIEW

**Comment by derekdowling** [comment]
How exactly is the settings file getting overwritten for production? Manually?

**Comment by xkb** [comment]
Yeah, I couldn't figure out a better and easy way. Suggestions welcome!

**Comment by derekdowling** [comment]
Fine by me for now :+1: There's probably a way to do it using gulp to choose what settings.js file is used, but overkill for just trying to get this thing deployed right now.

**Comment by xkb** [comment]
Give me a few minutes.

**Comment by xkb** [comment]
This is ugly but the best I can do with this gulp setup.

**Comment by derekdowling** [comment]
:+1:

**Pull request merged**
