### PR TITLE
Signals for Author/CachedAuthor

### PR DESCRIPTION
**Pull request by mraypold**
- Signals to prevent update anomalies between Author/CachedAuthor
- Minor changes in admin panel to prevent deletion of CachedAuthor
- Removal of unused code/imports

### CODE REVIEW

**Comment by xkb** [comment]
Neater solution!  
I suspect that you will also be creating CachedAuthor instances on external requests?

**Comment by mraypold** [comment]
Yep. CachedAuthors will be created when a foreign author is added to an Author's following list. Next PR.

**Comment by xkb** [comment]
Makes sense. How about invalidation or deletion of foreign authors? Or do we just keep them forever and update them on external requests if they exist?

**Comment by mraypold** [comment]
Currently they are being kept forever. I'm not sure how we would go about handling that.

**Comment by xkb** [comment]
👍

**Pull request merged**
