### PR TITLE
FRONTEND_HOST trailing slash

### PR DESCRIPTION
**Pull request by xkb**
My last PR broke the logout test since I changed the call. 
Also, `FRONTEND_HOST` shouldn't have a trailing slash to match `HTTP_HOST`

### CODE REVIEW

**Comment by mraypold** [comment]
I didn't notice this until after I merged PR #212 

Logout test is fixed now.

**Comment by xkb** [comment]
Changed it this just to remove the trailing slash

**Comment by xkb** [comment]
needs a review.

**Comment by derekdowling** [comment]
I ~THINK~ this should be okay :+1:

**Pull request merged**
